const darkTheme = {
  white: "#ffffff",
  background: "#2e384d",
  backgroundCountdown: "#222222",
  backgroundChallengeBox: "#222222",
  backgroundExperienceBar: "#c7c7c7",
  modalOpacityBackgroundColor: "rgba(34, 34, 34, 0.8)",
  text: "#4cd62b",
  textHighlight: "#4c30ec",
  title: "#4cd62b",
  experience: "#4cd62b",
  experienceGlowing: "rgba(76, 214, 43, 0.94)",
  emptyExperience: "gray",
  countdownButton: "#3f10ac",
  countdownButtonText: "#ffffff",
  countdownButtonHover: "#532dac",
  countdownButtonActive: "purple",
  countdownButtonActiveHover: "#2aa9e0",
  countdownButtonTextActive: "#ffffff",
  red: "#e83f5b",
  green: "#4cd62b",
  blue: "#5965e0",
  blueDark: "#3f10ac",
  blueTwitter: "#2aa9e0",
};

const lightTheme = {
  white: "#ffffff",
  background: "#e9e9e9",
  backgroundCountdown: "#ffffff",
  backgroundChallengeBox: "#ffffff",
  backgroundExperienceBar: "#c7c7c7",
  modalOpacityBackgroundColor: "rgba(0, 0, 0, 0.5)",
  text: "#4c30ec",
  textHighlight: "#4c30ec",
  title: "#4c30ec",
  experience: "#4c30ec",
  experienceGlowing: "rgba(76, 48, 236, 0.94)",
  emptyExperience: "lightgray",
  countdownButton: "#3f10ac",
  countdownButtonText: "#ffffff",
  countdownButtonHover: "#532dac",
  countdownButtonActive: "#eb7a10",
  countdownButtonTextActive: "#ffffff",
  red: "#e83f5b",
  green: "#a15397",
  blue: "#329fad",
  blueDark: "#3f10ac",
  blueTwitter: "#2aa9e0",
};

export { darkTheme, lightTheme };
